# Generated by Django 3.1.1 on 2020-09-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='name_kr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
